#pragma once
#include <ntddk.h>

#define IOCTL_AUDGUARD_POLL_EVENTS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)		
#define IOCTL_AUDGUARD_USER_DIALOG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)		


namespace client
{
	NTSTATUS create_close(PDEVICE_OBJECT DeviceObject, PIRP Irp);
	NTSTATUS device_control(PDEVICE_OBJECT DeviceObject, PIRP Irp);
	NTSTATUS forward(PDEVICE_OBJECT DeviceObject, PIRP Irp);
}

